# Generated by Django 6.0.1 on 2026-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("poste", models.CharField(max_length=100)),
                ("salaire", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
